# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Celdas_Personalizadas' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Celdas_Personalizadas
	pod "TGLParallaxCarousel"
	pod 'AlamofireImage', '~> 2.0'

end
